

START TRANSACTION;


USE dadb;

DROP TABLE IF EXISTS alg;
DROP TABLE IF EXISTS algcat;
DROP TABLE IF EXISTS algdavl;
DROP TABLE IF EXISTS algparam;
DROP TABLE IF EXISTS algparamtest;
DROP TABLE IF EXISTS algparamtype;
DROP TABLE IF EXISTS algstate;
DROP TABLE IF EXISTS algtrainparam;
DROP TABLE IF EXISTS algtype;
DROP TABLE IF EXISTS algtypeparam;
DROP TABLE IF EXISTS an;
DROP TABLE IF EXISTS clean;
DROP TABLE IF EXISTS cntx;
DROP TABLE IF EXISTS cntxan;
DROP TABLE IF EXISTS cntxanstrucstat;
DROP TABLE IF EXISTS cntxanstvarfpstat;
DROP TABLE IF EXISTS cntxstrucstat;
DROP TABLE IF EXISTS cntxstvarfpstat;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS eventcat;
DROP TABLE IF EXISTS eventstrucstat;
DROP TABLE IF EXISTS eventstvaranom;
DROP TABLE IF EXISTS opdat;
DROP TABLE IF EXISTS opdatcat;
DROP TABLE IF EXISTS opdatparam;
DROP TABLE IF EXISTS opdatparamtype;
DROP TABLE IF EXISTS paramtype;
DROP TABLE IF EXISTS prj;
DROP TABLE IF EXISTS prjan;
DROP TABLE IF EXISTS prjstate;
DROP TABLE IF EXISTS rev;
DROP TABLE IF EXISTS spacedavl;
DROP TABLE IF EXISTS split;
DROP TABLE IF EXISTS splitcat;
DROP TABLE IF EXISTS splitparam;
DROP TABLE IF EXISTS splitparamtype;
DROP TABLE IF EXISTS test;
DROP TABLE IF EXISTS testparam;
DROP TABLE IF EXISTS train;
DROP TABLE IF EXISTS trainparam;
DROP TABLE IF EXISTS trainstrucstat;
DROP TABLE IF EXISTS usr;
DROP TABLE IF EXISTS varcat;

