alg(idAlg,idAlgState,idAlgCat,nam,descr,fileRefProc)
algcat(idAlgCat,idAlgCatPar,nam,descr)
algcntxrnk(idAlgCntxRnk,idAn,idDescrCapStat,idPredCapStat,idExplCapStat,idSpaceDAVl)
algcntxrnknorm(idAlgCntxRnkNorm,idAn,idDescrCapStat,idPredCapStat,idExplCapStat,idSpaceDAVl)
algdavl(idAlgDAVl,nam,descr,ordine)
algparam(idAlgParam,idAlgParamType,idAlg,vl)
algparamtest(idAlgParamtest,idAlgParam,idTrain,idAlgParamType,vl)
algparamtype(IdAlgParamType,IdParamType,idAlg,nam,descr,vlDefault)
algrnk(idAlgRnk,idAlg,nReq,idAlgDAVl)
algstate(idAlgState,nam,descr)
algtrainparam(idAlgTrainParam,idAlgParam,idTrain,idAlgParamType,vl)
algtypeparam(idAlgParamType,nam,descr,unit)
an(idAn,idPrj,idAlg,nam,descr)
ancntx(IdAnCntx,IdAn,IdCntx,IdSplitType,nam,descr,fileRefTrainDat ,fileRefTestDat ,Regr_Outcome,Regr_Vars ,Regr_CtrlMethod,Regr_ModelMethods)
ancntxstrucstat(idStatDatiAnCntx,IdAnCntx,note,nCols,nRows,colTypes,units,cntxProjection)
ancntxstvarfpstat(IdAnCntxStVarFpStat,IdAnCntx,idStVar,note,nMeasures,mod,mn,mx,mean,sd,var,varCoef,filtr)
clean(idClean,idPrj,Note,ctsd,cnsd,cusd,filters)
cntx(idCntx,idPrj,idEvnt,nam,descr,fileRefDat ,ctsd,cnsd,cusd)
cntxstrucstat(idCntxStrucStat,idCntx,note,nCols,nRows,colTypes,units,evntProjection)
cntxstvarfpstat(idStatDaticntxVar,idCntx,idStVar,note,nMeasures,mod,mn,mx,mean,sd,var,varCoef,filtr)
comp2stvarsindstat(idComp2StVarsIndStat,idRev,idStVar1,idStVar2,note,chi2,df,pval,phi,coefPartialContg,vCramer,verosimiglianza)
compfpstat(idCompFpStat,idRev,note,modeRsd,minRsd,maxRsd,rmeanRsd,sdRsd,varRsd,varCoefRsd)
compres2stvarscorrstat(idCompRes2StVarsCorrStat,idRev,idStVar1,idStVar2,note,r,95CI,t,Spearman,Pearson)
compres2stvarsindstat(idCompRes2StVarsIndStat,idRev,idStVar1,idStVar2,note,chi2,df,pval,phi,coefPartialContg,vCramer,verosimiglianza)
compresfpstat(idCompResFpStat,idRev,note,modeRsd,minRsd,maxRsd,rmeanRsd,sdRsd,varRsd,varRsdCoef)
descrcapstat(idDescrCapStat,idTrainStVarFpStat,idTrainResStVarFpStat,note,dMin,dMax,dMean,dSd,dVar,dVarCoef)
evnt(idEvnt,idPrj,idEvntCat,nam,descr,fileRefRepoDat ,fileRefEvntDat)
evntanom(idEvntStVarAnom,idEvnt,nAnom,nNA,nErr,nOtherAnom,nCorrections)
evntcat(idEvntCat,idEvntCatPar,nam,descr)
evntstrucstat(idEvntStrucStat,idEvnt,note,nCols,nRows,colTypes,units)
evntstvaranom(idEvntStVarAnom,idStVar,idEvnt,nAnom,nNA,nErr,nOtherAnom,NaMap,errMap,errVlMap,otherAnomMap,nCorrections,correctionsMap)
explcapstat(idExplCapStat,idComp2StVarsCorrStat,idCompRes2StVarsCorrStat,note,dr,d95CI,dt,dSpearman,dPearson)
opdat(idOpDat,idClean,idOpDatCat,nam,descr,execOr)
opdatcat(idOpDatCat,idOpDatCatPar,nam,descr)
opdatparam(idTestParam,idOpDat,idParamType,vl)
opdatparamtype(idOpDatParamType,idOpDat,idParamType)
paramtype(idParamType,idParamTypeCat,nam,descr,unit,vlDefault)
paramtypecat(idParamTypeCat,idParamTypeCatPar,nam,descr)
predcapstat(idPredCapStat,idTestStVarFpStat,idTestResStVarFpStat,note,dMin,dMax,dMean,dSd,dVar,dVarCoef)
prj(idPrj,idUsr,nam,descr,folderRef ,idPrjState)
prjan(idPrj,idAn)
prjstate(idPrjState,nam,descr)
rcoltype(idRColType,nam,descr)
rev(IdRev,IdAn,Note)
rnk(idRnk,idAn,note)
spacedavl(idSpaceDAVl,nam,descr,ordine)
split(idSplit,idSplitType,idCntxAn,nam,descr,note)
splitcat(idSplitCat,idSplitCatPar,nam,descr)
splitparam(idSplitParam,idSplit,idParamType,vl)
splitparamtype(idSplitParamType,idSplit,idParamType)
splittype(IdSplitType,IdSplitCat,Nam,Descr,Perc)
stvar(idStVar,nam,descr,unit)
stvarcat(idStVarCat,idStVarCatPar,nam,descr)
test(idTest,idAn,fileRefTestDat ,fileRefTestRsdat ,note)
testparam(idTestParam,idAlgAn,idParamType,idTest,vl)
testresstrucstat(idTestResStrucStat,idTest,note,nCols,nRows,colTypes,units)
testresstvarasimstat(idTestResStVarAsimStat,idTest,idStVar,note,aritMode,coefPearson1,coefPearson2)
testresstvarcentresstat(idTestResStVarCentresStat,idTest,idStVar,note,arit,geom,quad,harm,mod,med)
testresstvarfpstat(idTestResStVarFpStat,idTest,idStVar,note,nMeasures,mod,mn,mx,mean,sd,var,varCoef)
teststrucstat(idTestStrucStat,idTest,note,nCols,nRows,colTypes,units)
teststvarasimstat(idTestStVarAsimStat,idTest,idStVar,note,aritMode,coefPearson1,coefPearson2)
teststvarfpstat(idTestStVarFpStat,idTest,idStVar,note,nMeasures,mod,mn,mx,mean,sd,var,varCoef)
train(idTrain,idAn,fileRefTrainDat ,fileRefTrainRsdat ,note)
trainparam(idTrainParam,idAlgAn,idParamType,idTrain,vl)
trainresstrucstat(idTrainResStrucStat,idTrain,note,nCols,nRows,colTypes,units)
trainresstvarasimstat(idTrainResStVarAsimStat,idTrain,idStVar,note,aritMode,coefPearson1,coefPearson2)
trainresstvarcentresstat(idTrainResStVarCentresStat,idTrain,idStVar,note,arit,geom,quad,harm,mod,med)
trainresstvarfpstat(idTrainResStVarFpStat,idTrain,idStVar,note,nMeasures,mod,mn,mx,mean,sd,var,varCoef)
trainstrucstat(idTrainStrucStat,idTrain,note,nCols,nRows,colTypes,units)
trainstvarasimstat(idTrainStVarAsimStat,idTrain,idStVar,note,aritMode,coefPearson1,coefPearson2)
trainstvarfpstat(idTrainStVarFpStat,idTrain,idStVar,note,nMeasures,mod,mn,mx,mean,sd,var,varCoef)
usr(idUsr,usrNam ,pwd ,firstnam,nam,eMail)
